#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The policy-routing apply script, generated by the real code and RUN.

WHY THIS EXISTS. WireGuard field report (v3.1.6, 2026-09-14): source-IP rules to a WGC
target did not route through the tunnel while OVPN targets did, with every rule, mark and
prohibit visibly in place. Nothing in the tree had ever executed the script the generator
writes; the v3.1.3 metal run proved the ip-rule half with an EMPTY tunnel table. Two gaps
against VPN Director's WireGuard path were closed in v3.1.7:
  * the chain restored whatever connmark code a flow carried and RETURNed on any non-zero
    mark, so a flow marked for a code whose rule was gone (target changed WGC1 -> WGC2, the
    very thing the reporter tried) kept that code, matched nothing in the 9000 band and fell
    to the WAN. It now restores only codes that are in use.
  * the flow-cache bypass a WGC rule needs was skipped when the client interface was down at
    apply time and never installed later. The apply now records it as `pending` and
    start_wgc() re-runs the apply (pinned by reaper_static_checks pbr-reassert).

WHAT IT DOES. Extracts ppbr_target(), ppbr_selector() and its helpers, the skip-list
helpers and ppbr_gen() from the real rc/reaper_pbr.c (brace-matched), compiles them on the
host with stubs for nvram, logmessage, ipv6_enabled, the OpenVPN client-enabled query and
the object resolver (the real reaper_nv.h helper is included as is), generates the script
for a four-rule list (src->WGC1 with the Killswitch on, src->OVPN2, ipset->WAN, mac->WGC1),
then RUNS it under fake iptables/ip6tables/ip/ipset/fc/logger/nvram that record their
arguments, with the kernel's skip-list proc file and /sys/class/net stood in by temp files.
Asserts, on the script text and the recorded calls:
  - the chain restores exactly the codes in use (2, 6, 11), one CONNMARK --restore-mark
    per code per family, and never an unused code; the RETURN follows them and precedes the
    first selector rule;
  - one mark rule per selector entry with the right code; the ip rules at 9002 / 9006 /
    9011 and the prohibit at 9106 only (OVPN2's Killswitch is off);
  - expect / expect_rules / expect_rules6 / failcount hold 6 / 4 / 4 / 0 and the script
    exits 0;
  - the source's bypass is recorded `new` when wgc1 exists, `pending` when it does not (with
    the "installed when the client starts" log line), and the LAN-wide bypass for the MAC
    rule is `new` either way; `fc flush` runs because a WG rule exists;
  - the script passes `sh -n` and, when a busybox is on the host, `busybox sh -n`.
Exit 0 pass, 1 fail, 77 skipped (no gcc, or no router source tree - pass the tree's
release/src/router as argv[1] or REAPER_ROUTER_SRC).
"""
import os, re, shutil, subprocess, sys, tempfile

def skip(msg):
    print("SKIP: " + msg); sys.exit(77)

def die(msg):
    print("FAIL: " + msg); sys.exit(1)

src_root = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("REAPER_ROUTER_SRC", "")
pbr = os.path.join(src_root, "rc", "reaper_pbr.c") if src_root else ""
nvh = os.path.join(src_root, "rc", "reaper_nv.h") if src_root else ""
if not pbr or not os.path.isfile(pbr) or not os.path.isfile(nvh):
    skip("no router source tree (pass release/src/router as argv[1] or REAPER_ROUTER_SRC)")
if not shutil.which("gcc") and not shutil.which("cc"):
    skip("no host C compiler")
CC = shutil.which("gcc") or shutil.which("cc")

def extract(src, signature):
    i = src.find(signature)
    if i < 0: die("signature not found in reaper_pbr.c: %r" % signature)
    j = src.index("{", i); depth = 0; k = j
    while k < len(src):
        c = src[k]
        if c == "{": depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0: return src[i:k + 1]
        k += 1
    die("unbalanced braces after %r" % signature)

with open(pbr, encoding="utf-8", errors="replace") as f:
    source = f.read()

td = tempfile.mkdtemp(prefix="pbrapply-")
try:
    SKIP = os.path.join(td, "skip_wireguard_network")
    PDIR = os.path.join(td, "reaper_pbr"); os.mkdir(PDIR)
    SYSNET = os.path.join(td, "sysnet"); os.mkdir(SYSNET)

    # the generator's own #defines, with the two kernel/tmp paths pointed at this dir.
    # They are used in string concatenation, so they must stay string LITERALS.
    defs = []
    for m in re.finditer(r"^#define\s+(PPBR_[A-Z0-9_]+)\s+(.*)$", source, re.M):
        name, val = m.group(1), m.group(2)
        if name == "PPBR_DIR": val = '"%s"' % PDIR
        elif name == "PPBR_BLOG_SKIP": val = '"%s"' % SKIP
        elif name == "PPBR_CACHE": val = '"%s/jffs"' % td
        defs.append("#define %s %s" % (name, val))
    m = re.search(r"typedef struct \{\s*int enable;\s*char \*rulelist;[^}]*\} ppbr_cfg_t;", source)
    if not m: die("ppbr_cfg_t typedef not found")
    cfg_t = m.group(0)

    STUBS = r'''
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/stat.h>
#include "reaper_nv.h"
#define RFW_SETS "%(td)s/sets.sh"
static FILE *LOG;
void logmessage(const char *tag, const char *fmt, ...) { va_list ap; va_start(ap, fmt); fprintf(LOG, "%%s: ", tag); vfprintf(LOG, fmt, ap); fputc('\n', LOG); va_end(ap); fflush(LOG); }
static const char *NV[][2] = { {"wgc1_enforce","1"}, {"wgc1_enable","1"}, {"vpn_client2_enforce","0"}, {"wgc2_enforce","1"}, {"wgc2_enable","0"}, {NULL,NULL} };
static const char *nvget(const char *k) { int i; for (i = 0; NV[i][0]; i++) if (!strcmp(NV[i][0], k)) return NV[i][1]; return ""; }
int nvram_get_int(const char *k) { return atoi(nvget(k)); }
int nvram_match(const char *k, const char *v) { return !strcmp(nvget(k), v); }
int ipv6_enabled(void) { return 1; }
int ovpn_is_client_enabled(int unit) { return 1; }
char *reaper_fw_list_get(const char *which) { return ""; }
int _vstrsep(char *buf, const char *sep, ...) { va_list ap; char **p; int n = 0; va_start(ap, sep); while ((p = va_arg(ap, char **)) != NULL) { *p = strsep(&buf, sep); if (!*p) break; n++; } va_end(ap); return n; }
#define vstrsep(buf, sep, args...) _vstrsep(buf, sep, args, NULL)
/* the object layer: every named object is a routable host/cidr object here */
static int ppbr_resolve_object(const char *name, char *out, size_t ol) { snprintf(out, ol, "%%s", name); return 1; }
''' % {"td": td}
    parts = [
        STUBS, "\n".join(defs), cfg_t,
        extract(source, "static int ppbr_ok("),
        extract(source, "static int ppbr_norm_v4("),
        extract(source, "static int ppbr_norm_v6("),
        extract(source, "static int ppbr_target("),
        extract(source, "static int ppbr_selector("),
        extract(source, "static void ppbr_emit_skip_helpers("),
        extract(source, "static int ppbr_gen("),
    ]
    MAIN = r'''
int main(int argc, char **argv) {
	ppbr_cfg_t c; LOG = fopen(argv[3], "a");
	c.enable = 1; c.rulelist = argv[1];
	int r = ppbr_gen(argv[2], 0, &c);
	printf("gen=%d\n", r); return r == 1 ? 0 : 1;
}
'''
    csrc = os.path.join(td, "t.c")
    with open(csrc, "w") as f:
        f.write("\n".join(parts) + MAIN)
    exe = os.path.join(td, "t")
    p = subprocess.run([CC, "-std=gnu99", "-Wall", "-Wno-unused-function", "-Wno-unused-result", "-Wno-unused-variable",
                        "-I", os.path.dirname(nvh), "-o", exe, csrc], capture_output=True, text=True)
    if p.returncode != 0:
        die("host compile failed:\n" + p.stderr)
    if "warning" in p.stderr:
        die("host compile warnings:\n" + p.stderr)

    # the fakes: record every call; ip answers the LAN route query; nvram the LAN ifname
    binp = os.path.join(td, "bin"); os.mkdir(binp)
    def fake(name, body):
        pth = os.path.join(binp, name)
        with open(pth, "w") as f: f.write("#!/bin/sh\n" + body)
        os.chmod(pth, 0o755)
    # a delete must FAIL once there is nothing to delete, or the teardown's
    # `while iptables -D ...; do :; done` never ends - exactly as on a router
    fake("iptables", 'echo "iptables $*" >> "$FAKE_TRACE"; case " $* " in *" -D "*|*" -X "*) exit 1;; esac; exit 0\n')
    fake("ip6tables", 'echo "ip6tables $*" >> "$FAKE_TRACE"; case " $* " in *" -D "*|*" -X "*) exit 1;; esac; exit 0\n')
    fake("ipset", 'echo "ipset $*" >> "$FAKE_TRACE"; exit 0\n')
    fake("fc", 'echo "fc $*" >> "$FAKE_TRACE"; exit 0\n')
    fake("logger", 'echo "logger $*" >> "$FAKE_LOG"; exit 0\n')
    fake("nvram", 'case "$2" in lan_ifname) echo br0;; esac; exit 0\n')
    fake("usleep", 'sleep 0.02\n')
    fake("ip", 'echo "ip $*" >> "$FAKE_TRACE"\n'
               'if [ "$1" = "-4" ] && [ "$2" = route ] && [ "$3" = show ]; then echo "192.168.50.0/24 dev br0 proto kernel scope link src 192.168.50.1"; fi\n'
               'exit 0\n')
    env = dict(os.environ, PATH=binp + os.pathsep + os.environ.get("PATH", ""))

    RULES = ("1>wg rule>src>192.0.2.10>>>WGC1<1>ovpn rule>src>192.0.2.20>>>OVPN2"
             "<1>set rule>ipset>myobj>>>WAN<1>mac rule>mac>aa:bb:cc:dd:ee:ff>>>WGC1")
    fails = []
    def check(name, cond, detail=""):
        print(("ok   " if cond else "FAIL ") + name)
        if not cond: fails.append(name + (" - " + detail if detail else ""))

    def generate():
        script = os.path.join(PDIR, "apply.sh"); glog = os.path.join(td, "genlog")
        with open(glog, "w"): pass
        p = subprocess.run([exe, RULES, script, glog], capture_output=True, text=True)
        if p.returncode != 0: die("generator failed: %s %s %s" % (p.stdout, p.stderr, open(glog).read()))
        with open(script) as f: S = f.read()
        # the only edit: the kernel's /sys/class/net becomes a temp dir so the "interface
        # exists" branch can be exercised on a host
        S2 = S.replace("/sys/class/net/", SYSNET + "/")
        with open(script, "w") as f: f.write(S2)
        return script, S

    def run(script, wg_up):
        for f in ("expect", "expect_rules", "expect_rules6", "failcount", "skipnets"):
            try: os.unlink(os.path.join(PDIR, f))
            except OSError: pass
        with open(SKIP, "w"): pass
        d = os.path.join(SYSNET, "wgc1")
        if wg_up: os.makedirs(d, exist_ok=True)
        elif os.path.isdir(d): os.rmdir(d)
        trace = os.path.join(td, "trace"); flog = os.path.join(td, "flog")
        with open(trace, "w"): pass
        with open(flog, "w"): pass
        env["FAKE_TRACE"] = trace; env["FAKE_LOG"] = flog
        # `printf 'add %s ' net > $SKIP` is how the kernel's proc file is written; a plain
        # file cannot answer that, so the shell function stands in for the kernel: the
        # redirect has already truncated the file, the function appends the net as the
        # kernel would list it, and the script's own read-back then sees it.
        # `fc` is a POSIX shell builtin (the history editor) that shadows a PATH fake in
        # dash/bash; on the router it is Broadcom's flow-cache tool. A function wins.
        wrap = ('printf() { if [ "$1" = "add %%s " ]; then echo "$2" >> "$SKIP"; '
                'elif [ "$1" = "del %%s " ]; then :; else command printf "$@"; fi; }; '
                'fc() { echo "fc $*" >> "$FAKE_TRACE"; }; . "%s"' % script)
        p = subprocess.run(["sh", "-c", wrap], capture_output=True, text=True, env=env, cwd=td)
        def rd(n):
            try:
                with open(os.path.join(PDIR, n)) as f: return f.read().strip()
            except OSError: return None
        with open(trace) as f: T = f.read()
        with open(flog) as f: FL = f.read()
        return p.returncode, T, FL, {n: rd(n) for n in ("expect", "expect_rules", "expect_rules6", "failcount", "skipnets")}

    script, S = generate()
    # syntax, both shells the firmware can hand this to
    p = subprocess.run(["sh", "-n", script], capture_output=True, text=True)
    check("script passes sh -n", p.returncode == 0, p.stderr)
    if shutil.which("busybox"):
        p = subprocess.run(["busybox", "sh", "-n", script], capture_output=True, text=True)
        check("script passes busybox sh -n", p.returncode == 0, p.stderr)

    # the chain header, on the text
    restores = re.findall(r"-m connmark --mark 0x([0-9A-F])0000/\$MASK -j CONNMARK --restore-mark --nfmask \$MASK --ctmask \$MASK", S)
    check("restores exactly the codes in use (2, 6, B)", sorted(restores) == ["2", "6", "B"], repr(restores))
    check("no unconditional restore is left", "-A REAPER_PBR -j CONNMARK --restore-mark" not in S, "")
    ret = S.find("-m mark ! --mark 0x0/$MASK -j RETURN")
    check("the RETURN follows the restores and precedes the first selector rule",
          ret > S.rfind("--restore-mark") and 0 < ret < S.find("pbr_rule iptables"), "")
    check("a chain the loop declares only once (one for-T loop)", S.count("-N REAPER_PBR") == 1 and S.count("-m mark ! --mark 0x0/$MASK -j RETURN") == 1, "")

    # run with wgc1 present
    rc, T, FL, F = run(script, wg_up=True)
    check("wg up: script exits 0", rc == 0, T[-800:])
    check("wg up: restores issued for both families",
          "iptables -t mangle -A REAPER_PBR -m connmark --mark 0x60000/0x000F0000 -j CONNMARK --restore-mark --nfmask 0x000F0000 --ctmask 0x000F0000" in T
          and "ip6tables -t mangle -A REAPER_PBR -m connmark --mark 0x20000/0x000F0000 -j CONNMARK --restore-mark" in T
          and "--mark 0x10000/" not in T, T)
    check("wg up: one mark rule per selector entry with its code",
          "iptables -t mangle -A REAPER_PBR -m mark --mark 0x0/0x000F0000 -s 192.0.2.10 -j MARK --set-xmark 0x60000/0x000F0000" in T
          and "iptables -t mangle -A REAPER_PBR -m mark --mark 0x0/0x000F0000 -s 192.0.2.20 -j MARK --set-xmark 0x20000/0x000F0000" in T
          and "iptables -t mangle -A REAPER_PBR -m mark --mark 0x0/0x000F0000 -m set --match-set rwfw_myobj dst -j MARK --set-xmark 0xB0000/0x000F0000" in T
          and "ip6tables -t mangle -A REAPER_PBR -m mark --mark 0x0/0x000F0000 -m set --match-set rwfw6_myobj dst -j MARK --set-xmark 0xB0000/0x000F0000" in T
          and "iptables -t mangle -A REAPER_PBR -m mark --mark 0x0/0x000F0000 -m mac --mac-source aa:bb:cc:dd:ee:ff -j MARK --set-xmark 0x60000/0x000F0000" in T, T)
    # v3.1.9 (field report 2026-09-17): MARK does not terminate a chain and
    # --set-xmark overwrites, so before the guard every matching rule ran and the
    # LAST in the list decided - a broad source rule silently beat a specific
    # ipset rule above it. The guard is what makes the list read top-down.
    _mk = [l for l in T.splitlines() if "-A REAPER_PBR" in l and "-j MARK --set-xmark" in l]
    check("first match wins: every selector rule is guarded on an unset mark",
          bool(_mk) and all("-m mark --mark 0x0/" in l for l in _mk), "\n".join(_mk))
    check("first match wins: the guard precedes the selector and the target",
          bool(_mk) and all(l.index("-m mark --mark 0x0/") < l.index("-j MARK --set-xmark") for l in _mk),
          "\n".join(_mk))
    check("wg up: ip rules at 9002 / 9006 / 9011, prohibit at 9106 only",
          "ip -4 rule add fwmark 0x20000/0x000F0000 lookup ovpnc2 pref 9002" in T
          and "ip -4 rule add fwmark 0x60000/0x000F0000 lookup wgc1 pref 9006" in T
          and "ip -4 rule add fwmark 0x60000/0x000F0000 prohibit pref 9106" in T
          and "ip -4 rule add fwmark 0xB0000/0x000F0000 lookup main pref 9011" in T
          and "prohibit pref 9102" not in T and "prohibit pref 9111" not in T, T)
    check("wg up: counts 6 / 4 / 4 / 0", (F["expect"], F["expect_rules"], F["expect_rules6"], F["failcount"]) == ("6", "4", "4", "0"), repr(F))
    check("wg up: the source bypass and the LAN-wide bypass are recorded new",
          F["skipnets"] is not None and "192.0.2.10/32 new" in F["skipnets"] and "192.168.50.0/24 new" in F["skipnets"], repr(F["skipnets"]))
    check("wg up: fc flush because a WireGuard rule exists", "fc flush" in T, "")
    check("wg up: PREROUTING jump added", "iptables -t mangle -A PREROUTING -j REAPER_PBR" in T, "")

    # run with wgc1 absent
    rc, T, FL, F = run(script, wg_up=False)
    check("wg down: script still exits 0 (a down tunnel is not a failure)", rc == 0 and F["failcount"] == "0", T[-400:])
    check("wg down: the source bypass is recorded pending, the LAN-wide one new",
          F["skipnets"] is not None and "192.0.2.10/32 pending" in F["skipnets"] and "192.168.50.0/24 new" in F["skipnets"], repr(F["skipnets"]))
    check("wg down: says the bypass is installed when the client starts", "skip-bypass not installed yet (installed when the client starts)" in FL, FL)
    check("wg down: the mark and routing rules still go in", "lookup wgc1 pref 9006" in T and "-s 192.0.2.10 -j MARK" in T, "")

    if fails:
        print("\n%d check(s) failed:\n  " % len(fails) + "\n  ".join(fails)); sys.exit(1)
    print("all checks passed: the generated policy-routing script restores only live codes, records a pending bypass, and installs what it must")
finally:
    shutil.rmtree(td, ignore_errors=True)
