#!/bin/bash
# gen_provenance.sh - stamp the build's own provenance into the web UI.
#
# Reaper_About.asp shows the patch count, the pinned upstream base and the build
# date. Hardcoding those in the page means it confidently displays the WRONG
# numbers one release after somebody forgets to edit it - and on a page whose
# entire argument is "you can verify this", a stale figure is worse than no
# figure. So the build writes them, every time, from what it actually did.
#
# Emitted as a tiny JS file rather than nvram or a CGI: the About page is static
# and must stay that way (no runtime input, nothing to validate, no network),
# and a <script src> costs one cached request and no server work.
#
# Run BEFORE the vendor www install, from the source tree root. The output is
# gitignored, so a build never dirties the tree - which matters because
# cut_fleet.sh refuses to run on a dirty canon.
#
# Usage:  gen_provenance.sh <source-tree-root> [patch-count] [base-commit]
#   patch-count / base-commit default to the environment (PATCH_COUNT,
#   BASE_COMMIT) and then to "" - an empty field renders as a dash rather than
#   a wrong number.

case "${1:-}" in
  -h|--help) sed -n "2,21 p" "$0" | sed "s/^# \?//"; exit 0 ;;
esac
set -euo pipefail

SRC="${1:?usage: gen_provenance.sh <source-tree-root> [patch-count] [base-commit]}"
PC="${2:-${PATCH_COUNT:-}}"
BC="${3:-${BASE_COMMIT:-}}"

[ -d "$SRC/release/src/router/www" ] || {
	echo "gen_provenance: no www at $SRC/release/src/router/www" >&2; exit 1; }

# Take the WHOLE EXTENDNO, not just the Reaper_vX.Y.Z prefix. Since 2026-09-10
# the build stamps a channel into it (Reaper_v3.1.2_BETA), and the old pattern
# stopped at the version number - so a beta image carried "v3.1.2" on the About
# page while its filename and every other surface said _BETA, and
# reaper_verify's provenance-stamp check compared the two and failed the build.
# The variant tag IS stripped: _noMCP is reported separately in `variant`, and
# leaving it here would break that same comparison the other way round.
# Falls back to the old extraction if EXTENDNO is missing or malformed, so a
# tree without it still renders a version rather than a dash.
VER="$(sed -n 's/^EXTENDNO=\(.*\)$/\1/p' \
	"$SRC/release/src-rt/version.conf" 2>/dev/null | head -1 | sed 's/_noMCP$//' || true)"
case "$VER" in
	Reaper_v[0-9]*) ;;
	*) VER="$(grep -oE 'Reaper_v[0-9]+\.[0-9]+(\.[0-9]+)?[a-z]?' \
		"$SRC/release/src-rt/version.conf" 2>/dev/null | head -1 || true)" ;;
esac

# SOURCE_DATE_EPOCH when the caller sets it, so a reproducible build stays
# reproducible; otherwise now, in UTC (never local - the build host's zone is
# not interesting and would make two builds of one commit differ).
if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
	BUILT="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d 2>/dev/null || date -u +%Y-%m-%d)"
else
	BUILT="$(date -u +%Y-%m-%d)"
fi

OUT="$SRC/release/src/router/www/reaper_provenance.js"
# Values are build-controlled, not user- or network-controlled, but they still
# land in a page: keep them to a conservative charset so nothing can ever escape
# the JS string literal, whatever a future caller passes in.
clean() { printf '%s' "$1" | tr -cd 'A-Za-z0-9._-' | cut -c1-40; }

# variant: the build lib passes VARIANT (MCP|noMCP); fall back to deriving it
# from the build config so a plain `make` or a manual stamp still shows the
# right thing instead of a dash.
if [ -z "${VARIANT:-}" ]; then
	if grep -q '^RTCONFIG_REAPER_MCP=y' "$SRC/release/src/router/.config" 2>/dev/null; then
		VARIANT=MCP
	else
		VARIANT=noMCP
	fi
fi

cat > "$OUT" <<EOF
/* Generated by build-scripts/gen_provenance.sh - DO NOT EDIT, DO NOT COMMIT.
   Consumed by Reaper_About.asp. An empty string renders as a dash. */
var REAPER_PROV = {
	version: "$(clean "${VER#Reaper_}")",
	variant: "$(clean "${VARIANT:-}")",
	patches: "$(clean "$PC")",
	series:  "$(clean "${PATCH_SERIES:-}")",
	base:    "$(clean "$BC")",
	built:   "$(clean "$BUILT")"
};
EOF

echo "   provenance: version=${VER#Reaper_} patches=${PC:--} series=${PATCH_SERIES:--} base=${BC:--} built=$BUILT"
