#!/usr/bin/env python3
"""Refresh the on-router firmware update discovery files from the PUBLISHED
GitHub releases of one version.

The router's update check (rom/webs_scripts/reaper_webs_update.sh) greps
updates/manifest_3006.txt for PRODUCTID#VARIANT#, and the notes viewer
(reaper_webs_note.sh) fetches updates/notes/Reaper_v<X.Y.Z>.txt. Both were only
ever written by build-scripts/stage_release.ps1 (the maintainer's local ship
flow), so a version published through the CI hand-off shipped as GitHub
releases while the manifest still advertised the previous version and the
on-router check reported "up to date". This script closes that gap: it is run
once, after the per-model release matrix finishes, and rebuilds the three
discovery files from the release assets that were just published -- taking the
authoritative sha256 (from each release's SHA256SUMS asset) and byte size (from
the asset metadata), so the numbers always match what users actually download.

Per-model MERGE: only the models passed in are rewritten; any other model's
existing manifest line is preserved, so a single-model release never drops the
rest of the fleet.

Env in: GH_TOKEN, GITHUB_REPOSITORY, V (e.g. v2.3.2), VNUM (2.3.2),
        MODELS (space list of productids), DATE (YYYY-MM-DD).
Writes:  updates/manifest_3006.txt, releases/latest.json,
         updates/notes/Reaper_<V>.txt  (relative to CWD = repo root).
"""
import os
import re
import json
import sys
import urllib.request

TOK = os.environ.get("GH_TOKEN", "")
REPO = os.environ["GITHUB_REPOSITORY"]
V = os.environ["V"]            # tag version, with the leading v (v2.3.2)
VNUM = os.environ["VNUM"]      # numeric X.Y.Z the manifest compares (2.3.2)
DATE = os.environ["DATE"]
MODELS = os.environ["MODELS"].split()

# manifest productid -> latest.json short model key
SHORT = {"RT-BE96U": "BE96U", "RT-BE86U": "BE86U", "RT-BE88U": "BE88U",
         "GT-BE98": "BE98", "GT-BE98_PRO": "BE98Pro"}


def api(url, octet=False):
    req = urllib.request.Request(url)
    # Authenticate only when a token is actually present. This repository is
    # public, so a local recovery run -- refreshing the manifest by hand after a
    # manual publish -- needs no PAT; an unconditional "Bearer " header 401s
    # instead of falling back to anonymous. CI always sets GH_TOKEN, so the
    # workflow path is unchanged. Anonymous is rate-limited to 60 requests/hour
    # per IP; this script makes roughly one per model plus one listing.
    if TOK:
        req.add_header("Authorization", "Bearer " + TOK)
    req.add_header("Accept", "application/octet-stream" if octet
                   else "application/vnd.github+json")
    return urllib.request.urlopen(req, timeout=60).read()


def sha_map(assets):
    """Download a release's SHA256SUMS asset and map filename -> hash."""
    out = {}
    named = [n for n in assets if n.startswith("SHA256SUMS-")]
    if not named:
        return out
    body = api("https://api.github.com/repos/%s/releases/assets/%s"
               % (REPO, assets[named[0]]["id"]), octet=True).decode()
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        h, _, f = line.partition("  ")      # sha256sum: two spaces
        if not f:
            h, _, f = line.partition(" ")
        out[f.strip().lstrip("*")] = h.strip()   # strip binary-mode marker
    return out


def gather():
    """Return (manifest_lines dict, latest entries dict) for the given models."""
    lines = {}      # (productid, variant) -> manifest line
    latest = {}     # short model key -> [entry, ...]
    for prod in MODELS:
        tag = "%s-%s" % (V, prod)
        rel = json.loads(api("https://api.github.com/repos/%s/releases/tags/%s"
                             % (REPO, tag)))
        assets = {a["name"]: a for a in rel["assets"]}
        shas = sha_map(assets)
        entries = []
        for name, a in sorted(assets.items()):
            if not name.endswith(".pkgtb"):
                continue
            variant = "noMCP" if "noMCP" in name else "MCP"
            url = "https://github.com/%s/releases/download/%s/%s" % (REPO, tag, name)
            lines[(prod, variant)] = "%s#%s#%s#%s#%s#%s" % (
                prod, variant, VNUM, url, shas.get(name, ""), a["size"])
            entries.append({"file": name, "sha256": shas.get(name, ""),
                            "size": a["size"], "url": url})
        if not entries:
            sys.exit("no .pkgtb assets on release %s" % tag)
        latest[SHORT.get(prod, prod)] = entries
    return lines, latest


def write_manifest(new_lines):
    # keep this header byte-identical to build-scripts/stage_release.ps1 so the
    # two writers (local ship / CI publish refresh) never churn each other.
    hdr = ("# Reaper firmware update manifest (3006 line) - generated by stage_release.ps1\n"
           "# format: PRODUCTID#VARIANT#VERSION#DOWNLOAD_URL#SHA256#SIZE\n"
           "# (sha256+size consumed by reaper_webs_upgrade.sh Phase 2 in-GUI install;\n"
           "#  Phase 1 firmware ignores the extra fields)\n")
    merged, order = {}, []
    if os.path.exists("updates/manifest_3006.txt"):
        for line in open("updates/manifest_3006.txt"):
            if line.startswith("#") or not line.strip():
                continue
            p = line.rstrip("\n").split("#")
            if len(p) < 2:
                continue
            key = (p[0], p[1])
            merged[key] = line.rstrip("\n")
            order.append(key)
    for key, line in new_lines.items():
        if key not in merged:
            order.append(key)
        merged[key] = line
    with open("updates/manifest_3006.txt", "w", newline="\n") as fh:
        fh.write(hdr + "\n".join(merged[k] for k in order) + "\n")


def write_latest(new_latest):
    latest = {"models": {}}
    if os.path.exists("releases/latest.json"):
        latest = json.load(open("releases/latest.json"))
    latest["version"] = V
    latest["date"] = DATE
    latest.setdefault("models", {})
    for short, entries in new_latest.items():
        latest["models"][short] = entries
    # releases/ no longer holds the images (they are GitHub release assets), so
    # the directory's existence must not be load-bearing: a checkout that has
    # never had one would otherwise fail here and take the publish workflow -
    # and with it the router's update manifest - down with it.
    os.makedirs("releases", exist_ok=True)
    with open("releases/latest.json", "w", newline="\n") as fh:
        json.dump(latest, fh, indent=2)
        fh.write("\n")


def demark(s):
    """Strip markdown emphasis/code markers for the plain-text viewer."""
    s = re.sub(r"\*\*(.+?)\*\*", r"\1", s)
    return s.replace("*", "").replace("`", "").strip()


def write_note():
    """On-router 'what's new' = the CHANGELOG section for this version, formatted
    for the .notebox viewer (white-space:pre-wrap monospace). Each changelog
    bullet '- **Headline.** body' becomes a marked headline line, a blank line,
    then the body, with a blank line between items so it scans instead of reading
    as a wall of text. Falls back to a generic pointer when no section exists."""
    os.makedirs("updates/notes", exist_ok=True)
    raw, on = [], False
    if os.path.exists("docs/CHANGELOG.md"):
        for line in open("docs/CHANGELOG.md", encoding="utf-8"):
            if line.startswith("## " + V + " ") or line.rstrip() == "## " + V:
                on = True
                continue
            if on and line.startswith("## "):
                break
            if on:
                raw.append(line.rstrip("\n"))

    out, items = ["Reaper %s" % V, ""], 0
    for line in raw:
        s = line.strip()
        if not s:
            continue
        m = re.match(r"^-\s+\*\*(.+?)\*\*[.:]?\s*(.*)$", s)   # "- **Headline.** body"
        if m:
            head, body = demark(m.group(1)).rstrip("."), demark(m.group(2))
            out.append("> " + head)
            if body:
                out += ["", body]
            out.append("")
            items += 1
        elif s.startswith("- "):                              # bullet without a bold lead
            out += ["> " + demark(s[2:]), ""]
            items += 1
        else:                                                 # lead paragraph, if any
            out += [demark(s), ""]

    if items == 0:
        note = ("Reaper %s is available.\n\nRelease notes: "
                "https://github.com/%s/releases\n" % (V, REPO))
    else:
        out.append("Full changelog: "
                   "https://github.com/%s/blob/main/docs/CHANGELOG.md" % REPO)
        note = "\n".join(out).rstrip() + "\n"
    with open("updates/notes/Reaper_%s.txt" % V, "w", newline="\n", encoding="utf-8") as fh:
        fh.write(note)


def main():
    new_lines, new_latest = gather()
    write_manifest(new_lines)
    write_latest(new_latest)
    write_note()
    print("refreshed manifest / latest.json / notes for %s (models: %s)"
          % (V, " ".join(MODELS)))


if __name__ == "__main__":
    main()
