<#
.SYNOPSIS
  RETIRED 2026-08-11 - do not run. Kept for reference only.

.NOTES
  The public clean-room CI workflow builds every model and the release workflow
  attaches the images straight from those build artifacts, so nothing needs a
  locally staged copy any more (owner, 2026-08-11: "the auto build workflow is
  now operational which makes staging no longer needed").

  Running this again would re-commit ~150 MB of .pkgtb per version into git,
  which is exactly what the 2026-08-11 cleanup removed - the images are GitHub
  Release ASSETS, which live outside the repo. releases/*.pkgtb and
  releases/**/SHA256SUMS*.txt are now gitignored, so a re-run would also silently
  stage nothing and then fail its own verify step.

  Still live and NOT replaced by CI: releases/latest.json and
  updates/manifest_3006.txt are regenerated by build-scripts/refresh_manifest.py
  (run by the publish workflow), which is what the router's update check reads.

.DESCRIPTION
  ORIGINAL PURPOSE (historical):
  Stage locally built Reaper firmware into releases/ for a per-model GitHub release.

.DESCRIPTION
  Copies the built .pkgtb images for a version from the local firmware ladder
  (asuswrt-merlin.ng\reaper-firmware\) into releases/<Model>/<MODEL>-REAPER-<ver>/,
  writes per-model SHA256SUMS files, verifies every copy hash-for-hash, refreshes
  releases/latest.json, and commits the result locally.

  Hardening (so a staged tree can never fail the publish workflow):
    * Canonical folder name is <MODEL>-REAPER-<ver> with UPPER-CASE "REAPER". Any
      pre-existing case variant (e.g. BE88U-Reaper-v2.1.2) is renamed to the
      canonical case in git — the release workflow globs case-sensitively on Linux,
      so a mis-cased folder would silently yield "no images".
    * Before committing, the script replicates the workflow's EXACT collect+verify
      logic against the git-tracked paths (case-sensitive folder + filename match,
      SHA256SUMS present, every model hash verified). If any requested model would
      fail CI, the script aborts WITHOUT committing and prints what's wrong.

  It NEVER pushes. Publishing is: git push origin main, then push a per-model tag
  v<version>-<MODEL> — .github/workflows/release.yml builds the GitHub Release from
  what was staged.

.EXAMPLE
  .\stage_release.ps1 -Version v2.1.2 -Models BE86U,BE88U,BE98
  .\stage_release.ps1 -Version v2.1.2 -ValidateOnly     # check staging is CI-clean, no changes
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidatePattern('^v\d+\.\d+\.\d+[0-9a-z._-]*$')]
    [string]$Version,

    [ValidateSet('BE96U', 'BE86U', 'BE88U', 'BE98', 'BE98Pro')]
    [string[]]$Models = @('BE96U', 'BE86U', 'BE88U', 'BE98', 'BE98Pro'),

    # Local firmware ladder holding the built images (default: sibling asuswrt-merlin.ng mirror)
    [string]$LadderDir,

    # Stage whatever images exist instead of requiring the full model matrix
    [switch]$AllowPartial,

    # Stage + write files but skip the git commit
    [switch]$NoCommit,

    # Only run the CI-parity validation against what's already staged; make no changes
    [switch]$ValidateOnly
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
if (-not $LadderDir) {
    $LadderDir = Join-Path (Split-Path -Parent $RepoRoot) 'asuswrt-merlin.ng\reaper-firmware'
}

$PrefixMap = @{
    BE96U   = 'RT-BE96U'
    BE86U   = 'RT-BE86U'
    BE88U   = 'RT-BE88U'
    BE98    = 'GT-BE98'
    BE98Pro = 'GT-BE98_PRO'
}

# Canonical release folder for a model key, relative to the repo root (forward
# slashes for git). UPPER-CASE REAPER — the workflow globs *-REAPER-<V> case-sensitively.
function Get-CanonicalRel { param([string]$m) "releases/$m/$($m.ToUpper())-REAPER-$Version" }

# If a folder differs from the canonical name only by case, rename it to canonical
# in git (two-step, because Windows/macOS filesystems are case-insensitive).
function Repair-FolderCase {
    param([string]$m)
    $canonRel = Get-CanonicalRel $m
    $parentRel = "releases/$m"
    $parentAbs = Join-Path $RepoRoot ($parentRel -replace '/', '\')
    if (-not (Test-Path $parentAbs)) { return }
    $canonLeaf = Split-Path $canonRel -Leaf
    Get-ChildItem -LiteralPath $parentAbs -Directory |
        Where-Object { $_.Name -ieq $canonLeaf -and $_.Name -cne $canonLeaf } |
        ForEach-Object {
            $srcRel = "$parentRel/$($_.Name)"
            $tmpRel = "$parentRel/__caserepair_$([guid]::NewGuid().ToString('N').Substring(0,8))"
            if (git -C $RepoRoot ls-files -- $srcRel) {
                git -C $RepoRoot mv -- $srcRel $tmpRel | Out-Null
                git -C $RepoRoot mv -- $tmpRel $canonRel | Out-Null
            } else {
                Rename-Item -LiteralPath $_.FullName -NewName (Split-Path $tmpRel -Leaf)
                Rename-Item -LiteralPath (Join-Path $parentAbs (Split-Path $tmpRel -Leaf)) -NewName $canonLeaf
            }
            Write-Host "case-normalized folder: $($_.Name) -> $canonLeaf" -ForegroundColor Yellow
        }
}

# Replicate the release workflow's collect+verify EXACTLY, against git-tracked paths
# (that is what the Linux runner checks out). Returns $true if every requested model
# would pass CI. Case-sensitive on purpose (mimics the runner).
function Test-CiParity {
    param([string[]]$CheckModels)
    $tracked = @(git -C $RepoRoot ls-files -- releases)
    $vEsc = [regex]::Escape($Version)
    $allOk = $true
    foreach ($m in $CheckModels) {
        $prefix = $PrefixMap[$m]; $pEsc = [regex]::Escape($prefix)
        $imgRe = "releases/[^/]+/[^/]+-REAPER-$vEsc/${pEsc}_3006_102\.8_Reaper_${vEsc}_.*nand_squashfs\.pkgtb$"
        $shaRe = "releases/[^/]+/[^/]+-REAPER-$vEsc/SHA256SUMS-${pEsc}-Reaper_$vEsc\.txt$"
        $imgs = @($tracked | Where-Object { $_ -cmatch $imgRe })
        $shas = @($tracked | Where-Object { $_ -cmatch $shaRe })
        if ($imgs.Count -eq 0) { Write-Host "  [CI-FAIL] $m ($prefix): no tracked image in a *-REAPER-$Version/ folder (wrong-case folder, or not staged/committed)" -ForegroundColor Red; $allOk = $false; continue }
        if ($shas.Count -eq 0) { Write-Host "  [CI-FAIL] $m ($prefix): no tracked SHA256SUMS-$prefix-Reaper_$Version.txt beside the images" -ForegroundColor Red; $allOk = $false; continue }
        $shaRel = $shas[0]; $dirRel = Split-Path $shaRel -Parent
        $bad = 0; $checked = 0
        foreach ($ln in @(git -C $RepoRoot show ":$shaRel" 2>$null)) {
            if ($ln -cmatch '^([0-9a-fA-F]{64})\s+(\S+)$') {
                $hash = $matches[1].ToLower(); $file = $matches[2]
                if ($file -notlike "${prefix}_*") { continue }   # CI verifies only " ${M}_" lines
                $checked++
                $abs = Join-Path $RepoRoot (($dirRel + '/' + $file) -replace '/', '\')
                if (-not (Test-Path -LiteralPath $abs)) { Write-Host "  [CI-FAIL] ${m}: SHA lists missing file $file" -ForegroundColor Red; $bad++; continue }
                if ((Get-FileHash -LiteralPath $abs -Algorithm SHA256).Hash.ToLower() -ne $hash) { Write-Host "  [CI-FAIL] ${m}: hash mismatch for $file" -ForegroundColor Red; $bad++ }
            }
        }
        if ($checked -eq 0) { Write-Host "  [CI-FAIL] $m ($prefix): SHA256SUMS has no ${prefix}_ lines" -ForegroundColor Red; $allOk = $false }
        elseif ($bad -gt 0) { $allOk = $false }
        else { Write-Host "  [CI-OK]   $m ($prefix): $($imgs.Count) image(s), $checked hash(es) verified, folder case OK" -ForegroundColor Green }
    }
    return $allOk
}

# ---------------------------------------------------------------- validate-only --
if ($ValidateOnly) {
    Write-Host "CI-parity validation for $Version (models: $($Models -join ', '))" -ForegroundColor Cyan
    if (Test-CiParity -CheckModels $Models) { Write-Host "`nAll requested models are CI-clean." -ForegroundColor Green; exit 0 }
    else { Write-Host "`nOne or more models would FAIL the publish workflow — fix before tagging." -ForegroundColor Red; exit 1 }
}

if (-not (Test-Path $LadderDir)) { throw "Firmware ladder not found: $LadderDir (pass -LadderDir)" }

# --- 1. Plan: confirm every expected image exists before touching anything ---
$plan = @(); $missing = @()
foreach ($m in $Models) {
    $prefix = $PrefixMap[$m]
    foreach ($variant in @('', '_noMCP')) {
        $file = "${prefix}_3006_102.8_Reaper_${Version}${variant}_nand_squashfs.pkgtb"
        $src = Join-Path $LadderDir $file
        if (Test-Path $src) { $plan += [pscustomobject]@{ Model = $m; Prefix = $prefix; File = $file; Src = $src } }
        else { $missing += $file }
    }
}
if ($missing.Count -gt 0) {
    $missing | ForEach-Object { Write-Host "MISSING: $_" -ForegroundColor Red }
    if (-not $AllowPartial) { throw "Not all images for $Version are in the ladder. Build them first, narrow -Models, or pass -AllowPartial." }
    Write-Host "continuing without the missing images (-AllowPartial)" -ForegroundColor Yellow
}
if ($plan.Count -eq 0) { throw "Nothing to stage for $Version." }

# --- 2. Copy, hash, verify, write per-model SHA256SUMS (canonical folder case) ---
$staged = @()
foreach ($group in ($plan | Group-Object Model)) {
    $m = $group.Name; $prefix = $PrefixMap[$m]
    Repair-FolderCase -m $m                                  # fix any BE88U-Reaper-* style variant first
    $destDir = Join-Path $RepoRoot ((Get-CanonicalRel $m) -replace '/', '\')
    New-Item -ItemType Directory -Force -Path $destDir | Out-Null
    $sums = @()
    foreach ($item in $group.Group) {
        $dest = Join-Path $destDir $item.File
        Copy-Item $item.Src $dest -Force
        $srcHash = (Get-FileHash $item.Src -Algorithm SHA256).Hash.ToLower()
        $dstHash = (Get-FileHash $dest    -Algorithm SHA256).Hash.ToLower()
        if ($srcHash -ne $dstHash) { throw "COPY VERIFICATION FAILED for $($item.File) — staged file does not match the built image" }
        $sums   += "$dstHash  $($item.File)"
        $staged += [pscustomobject]@{ Model = $m; File = $item.File; Sha256 = $dstHash; Size = (Get-Item $dest).Length }
        Write-Host ("staged  {0,-8} {1}" -f $m, $item.File)
    }
    # LF line endings so `sha256sum -c` works in CI
    $sumsPath = Join-Path $destDir "SHA256SUMS-$prefix-Reaper_$Version.txt"
    [System.IO.File]::WriteAllText($sumsPath, (($sums -join "`n") + "`n"))
}

# --- 3. Update the machine-readable manifest, merging with any existing entry ---
# NB: local var must NOT be named $models — PowerShell variable names are
# case-insensitive, so $models would alias the $Models param (which has a
# ValidateSet) and reassigning it throws a validation error.
$manifestPath = Join-Path $RepoRoot 'releases\latest.json'
$modelMap = [ordered]@{}
if (Test-Path $manifestPath) {
    try {
        $prev = Get-Content $manifestPath -Raw | ConvertFrom-Json
        if ($prev.version -eq $Version -and $prev.models) {
            foreach ($p in $prev.models.PSObject.Properties) { $modelMap[$p.Name] = $p.Value }  # keep models not re-staged this run
        }
    } catch { }
}
foreach ($group in ($staged | Group-Object Model | Sort-Object Name)) {
    $modelMap[$group.Name] = @(
        foreach ($s in $group.Group) {
            [ordered]@{ file = $s.File; sha256 = $s.Sha256; size = $s.Size
                        url = "https://github.com/TheUnboundDeveloper/AM-Reaper/releases/download/$Version-$($PrefixMap[$group.Name])/$($s.File)" }
        }
    )
}
$manifest = [ordered]@{ version = $Version; date = (Get-Date -Format 'yyyy-MM-dd'); models = $modelMap }
[System.IO.File]::WriteAllText($manifestPath, (($manifest | ConvertTo-Json -Depth 6) -replace "`r`n", "`n") + "`n")
Write-Host "wrote releases/latest.json"

# --- 3b. plain-text update manifest for the on-router check ----------------------
# reaper_webs_update.sh (busybox sh, cannot parse JSON) greps this by
# PRODUCTID#VARIANT. One line per model+variant, derived from the same $modelMap
# so it stays in lockstep with latest.json / the published releases.
$verNum = $Version.TrimStart('v')
$updDir = Join-Path $RepoRoot 'updates'
if (-not (Test-Path $updDir)) { New-Item -ItemType Directory -Path $updDir | Out-Null }
$txtLines = @('# Reaper firmware update manifest (3006 line) - generated by stage_release.ps1',
              '# format: PRODUCTID#VARIANT#VERSION#DOWNLOAD_URL#SHA256#SIZE',
              '# (sha256+size consumed by reaper_webs_upgrade.sh Phase 2 in-GUI install;',
              '#  Phase 1 firmware ignores the extra fields)')
foreach ($mp in $modelMap.GetEnumerator()) {
    foreach ($img in $mp.Value) {
        $productid = ($img.file -replace '_3006.*$', '')          # RT-BE96U / GT-BE98_PRO
        $variant   = if ($img.file -match '_noMCP_') { 'noMCP' } else { 'MCP' }
        $txtLines += "$productid#$variant#$verNum#$($img.url)#$($img.sha256)#$($img.size)"
    }
}
$manifestTxt = Join-Path $updDir 'manifest_3006.txt'
[System.IO.File]::WriteAllText($manifestTxt, (($txtLines -join "`n")) + "`n")
Write-Host "wrote updates/manifest_3006.txt"

# --- 4. Stage in git, then PROVE it is CI-clean before committing ----------------
git -C $RepoRoot add -- releases updates
Write-Host ""
Write-Host "CI-parity check (must pass before commit):" -ForegroundColor Cyan
$check = @($staged | Select-Object -ExpandProperty Model -Unique)
if (-not (Test-CiParity -CheckModels $check)) {
    throw "Staging is NOT CI-clean (see [CI-FAIL] above). Left staged (uncommitted) for inspection; nothing was committed."
}

if (-not $NoCommit) {
    git -C $RepoRoot commit -m "releases: stage firmware $Version"
    if ($LASTEXITCODE -ne 0) { throw "git commit failed" }
}

Write-Host ""
Write-Host "Staged $($staged.Count) images for $Version — all CI-clean." -ForegroundColor Green
Write-Host "Next steps (run when ready to publish):" -ForegroundColor Cyan
Write-Host "  git -C `"$RepoRoot`" push origin main"
Write-Host "  # Releases are PER-MODEL: push one tag v<version>-<MODEL> per model." -ForegroundColor DarkGray
foreach ($m in ($staged | Select-Object -ExpandProperty Model -Unique | Sort-Object)) {
    $tag = "$Version-$($PrefixMap[$m])"
    Write-Host "  git -C `"$RepoRoot`" tag $tag && git -C `"$RepoRoot`" push origin $tag"
}
